### ISSUE TITLE
Redmine3.1.1 not support time tracking plugin

### ISSUE THREAD

**Issue by johnp2686** [fernandokosh/redmine_time_tracker#105]
Hi,

I using redmine3.1.1 installed successfully time tracking plugin but i am getting
undefined method `includes' for {:conditions=>"1 = 1"}:Hash)

**Comment by phoebusnetto** [comment]
Did you try to replace with this?
<code>
where('1=1')
</code>

**Comment by johnp2686** [comment]
yes that issue is fixed but i am getting 

NameError (undefined local variable or method `connection' for #TimeLogQuery:0x007f4fb96cb000):

**Comment by phoebusnetto** [comment]
You have to change current <code>connection</code> in TimeLogQuery model to <code>self.class.connection</code> or create a method to return it:
<code>
def connection
    self.class.connection
end
</code>

**Comment by johnp2686** [comment]
Connection issue fixed i am getting NoMethodError (undefined method `joins' for #Hash:0x007fd42bd65c70):

**Comment by phoebusnetto** [comment]
Well... I guess you must adjust too much code to make it work on Redmine 3.1.

I did, but it is not OK yet. And you must see the fork from **HicknHack**, he has a version of Time Track compatible with 3.1 (I do not test it yet).

**Comment by johnp2686** [comment]
I tried HicknHack not working any other idea to resolve the issue

**Comment by phoebusnetto** [comment]
https://github.com/hicknhack-software/redmine_time_tracker

He is working on a complete rewrite of plugin, I am waiting its finish to test.

I tried to install the master version for this fork, but got CoffeeScript Comiple Error. BTW I'm using Windows machine with Bitnami Stack for Redmine app.
